# Generated by Django 5.1.2 on 2024-11-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrace', '0004_remove_mygraceadmin_address_remove_mygraceadmin_clan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygraceuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mygraceuser',
            name='community',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mygraceuser',
            name='lga_of_residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mygraceuser',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mygraceuser',
            name='state_of_residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
