# Generated by Django 5.1.2 on 2024-11-10 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrace', '0005_alter_mygraceuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('UPDATE', 'Profile Update'), ('PASSWORD_CHANGE', 'Password Change'), ('PROFILE_UPDATE', 'Profile Update'), ('VIEW_PROFILE', 'Profile View'), ('PROFILE_SEARCH', 'Profile Search'), ('VERIFICATION', 'Verification'), ('VERIFICATION_REQUEST', 'Verification Request')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
