# Generated by Django 5.1.2 on 2024-11-12 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrace', '0008_activitylog_details_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
