# Generated by Django 5.1.2 on 2024-11-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrace', '0010_remove_mygraceuser_role_alter_mygraceuser_clan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygraceadmin',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='ADMIN', max_length=10),
        ),
    ]
