# Generated by Django 5.1.2 on 2024-11-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mygrace', '0011_alter_mygraceadmin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygraceuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='mygraceuser_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='mygraceuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='mygraceuser_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='mygraceadmin',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='mygraceadmin_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='mygraceadmin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='mygraceadmin_permissions', to='auth.permission'),
        ),
    ]
