# Generated by Django 5.1.2 on 2024-11-13 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygrace', '0012_mygraceuser_groups_mygraceuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mygraceuser',
            old_name='address',
            new_name='addresses',
        ),
    ]
