# Generated by Django 5.1.2 on 2024-11-13 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygrace', '0013_rename_address_mygraceuser_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mygraceuser',
            old_name='addresses',
            new_name='address',
        ),
    ]
