# Generated by Django 5.1.2 on 2024-11-17 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrace', '0019_alter_verification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_descriptor', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_descriptor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
