# Generated by Django 5.1.2 on 2024-11-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrace', '0021_facerecognitiondata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mygraceuser',
            name='public_visibility',
        ),
        migrations.AlterField(
            model_name='facedescriptor',
            name='face_descriptor',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
