# Generated by Django 5.1.2 on 2024-11-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrace', '0022_remove_mygraceuser_public_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygraceuser',
            name='public_visibility',
            field=models.BooleanField(default=True),
        ),
    ]
