# Generated by Django 5.1.2 on 2024-11-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrace', '0024_facedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedescriptor',
            name='converted_face_descriptor',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
