# Generated by Django 5.1.2 on 2024-11-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrace', '0026_remove_facedescriptor_converted_face_descriptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedescriptor',
            name='converted_face_descriptor',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
