# Generated by Django 5.1.2 on 2024-11-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrace', '0028_debugfacematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedescriptor',
            name='numpy_face_descriptor',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
